### PR TITLE
Make urdf formats for OMPL envs and robots

### PR DESCRIPTION
**Pull request by aditya-vk**
OMPL provides envs and robots for benchmarking and different planners. They are provided separately in OMPLapp repository as .dae files. It should be convenient to have these in our assets as urdf files to load up any env and any robot and benchmark our planners. Example of an SE2 environment and robot is visualized below.

image

### CODE REVIEW

**Comment by sanjibanc** [comment]
Looks good to me!

**Comment by aditya-vk** [comment]
Awesome! Then I will do the same for SE3 environments as well and remove the WIP tag and notify you folks. Thanks!

**Comment by aditya-vk** [comment]
Done. Ready for a merge. 
@sanjibac @brianhou

**Comment by brianhou** [comment]
Are all of these files necessary? This doubles the size of `pr_assets`, and I don't think most people will ever use these planning environments. Would a separate planning benchmarks repository make sense?

**Pull request closed without merging**
