### PR TITLE
Ycb objects

### PR DESCRIPTION
**Pull request by vinitha910**
added kinbody files for ycb objects

### CODE REVIEW

**Comment by DavidB-CMU** [comment]
@vinitha910 Could you please explain which YCB objects you would like to add in Pull Requests 8 and 9?
Perhaps I can help you with this on Friday.
We have some newer, better-quality mesh models of the YCB objects so we should put those in pr-ordata.
Also, we should probably add all the YCB objects?  @mkoval  maybe in a separate directory?

**Comment by jeking04** [comment]
Alrighty, after looking through this I think several of these items are duplicated and already exist in the pr-ordata.

Here are the duplicates:

conference_table -> table
poptarts -> pop_tarts
template0 -> block

Lets remove all the files related to these objects. Also, since we had to give the pill bottle back I guess we should remove it as well.

Vinitha, sorry for not catching this sooner. Lets update the ycb scripts to load the new kinbody xml. Come find me and we can chat about what this entails.

Also, after talking to David we have decided to drop in all the google generated ycb object models as part of this pull request. We will put them in a directory: data/objects/ycb.  Lets move the pitcher to that same directory.

**Comment by vinitha910** [comment]
I deleted the duplicates, I will move the YCB objects into data/objects/ycb once it's created

**Comment by mkoval** [comment]
What is the relationship between this pull request and #10?

**Comment by DavidB-CMU** [comment]
This pull request is just for: 
pill bottle model, poptarts model, water pitcher/jug model, and json tags.

The water pitcher model can be removed from this PR because a better model is in PR #10

**Comment by mkoval** [comment]
@vinitha910 @DavidB-CMU Can we close this now that the #10 is resolved?

**Comment by jeking04** [comment]
Okay, I think this PR is mostly obsolete. There is already a poptarts model in master. The pill bottle is fairly useless (just a cylinder) and I think we can go ahead and just let that one go. And as @DavidB-CMU pointed out there is a better model of the pitcher in the gitlab repo. The only remaining useful piece of this PR is the tag data for the pitcher. Did we decide that we should put tag data for gitlab objects in this the `tag_data.json` in this repo?

**Comment by mkoval** [comment]
@jeking04 @vinitha910 What is the status of this?

**Comment by jeking04** [comment]
Okay, here is what I think we need to do to finish off this PR:
- [ ] Remove pill bottle - we don't have that bottle anymore, and it was pretty useless
- [ ] Remove poptarts files - there is already a poptarts model in master
- [ ] Replace the pitcher model with the one from the ycb dataset: https://git.personalrobotics.ri.cmu.edu/pr_data/ycb_objects
- [ ] Check/update the tag data to be consistent with the new pitcher model

**Comment by vinitha910** [comment]
I made all the requested changes @jeking04 @mkoval The branch can be merged with master

**Comment by mkoval** [comment]
This pull request accidentally deleted the `pop_tarts` model. I fixed it in a84fb2e.

**Pull request merged**
