### PR TITLE
Add YCB objects to pr-ordata

### PR DESCRIPTION
**Pull request by DavidB-CMU**
@jeking04 @mkoval 
This pull request is for the ycb_objects branch of pr-ordata, but I think it will be merged into master eventually.

This adds 59 of the 77 objects in the YCB dataset [1].  
The other objects can not be scanned, because they're either too small, transparent, or non-rigid.
The textured models were created by Google and converted to Collada by us.  
There's 93 kinbody files which can be loaded into OpenRAVE or Rviz.  
Total size is 776 MB, with texture maps being the largest files.  

Is this file size ok?  should we make it a separate package?  maybe try down-sampling the texture maps?

[1] "Benchmarking in Manipulation Research: Using the Yale-CMU-Berkeley Object and Model Set"  http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7254318

### CODE REVIEW

**Comment by DavidB-CMU** [comment]
Btw, checkout the pitcher model 019, it's much better quality.

**Comment by mkoval** [comment]
> Total size is 776 MB, with texture maps being the largest files.

After some further thought, I think this is too big for Github. Github is unhappy if a repository is greater than 1 GB, which doesn't leave us with much headroom. This is especially an issue if we ever have to edit these models.

@ClintLiddick Thoughts? Where can we put this?

**Comment by ClintLiddick** [comment]
If the objects are just meshes, we have a couple options. I think the "best" is to keep them in gitlab (so we'll always have old versions), and if necessary we can "release" them as a package or as a tarball on the website. If it's not important to maintain history, we can just keep them on /data and release publicly as necessary.

**Comment by siddhss5** [comment]
+1 for this idea. That was the whole point behind the gitlab effort, right?

Sidd.

(Rapidly written in motion)

**Comment by DavidB-CMU** [comment]
These files are a pre-release sub-set of a larger database of models that will be in the public domain as individual tarballs on the YCB website. 

If we want to pull the models from gitlab (or our website), perhaps we should mirror the official set of models (multiple gigabytes) and then have a script that the user can download the required subset of files into the pr_ordata package?

In terms of historical data and maintainability, I think we should keep only one tarball for each model. If a better quality scan is done, then we replace the model file. There are already multiple resolutions for each object, so the texture quality and scan geometry can only get better as technology improves. But if a model is removed from the official database, we keep it on our mirror. 
Here are some examples of this: 
- The original YCB website published 9 object models which will no longer be on the new forthcoming website. 
- I read a paper that used objects from the KIT database. Two of those objects are no longer available on the official website.

**Comment by schelian** [comment]
Hi, I'm late to join this but very much interested b/c our group wants hi-res scans of objects as well.

David said there are new scans.  Which scanner was used?  How is the conversion process done from the scans to Kinbody files?  There is also mention of textured models being created by Google and converted to Collada, etc.  Which scanner was used for textured objects?  If this is easier to discuss over a telephone call, that'd be great too!

It is my understanding that many scanners output a mesh of points in STL format; it is also possible to go from that to a surface representation such as Polyworks; a surface representation can also be used to create an content tree which would be useful for articulated objects.

**Comment by mkoval** [comment]
I'm not sure - @Shushman or @DavidB-CMU can you reply to @schelian's questions?

**Comment by DavidB-CMU** [comment]
@schelian Hi, I will call you on the telephone today.

**Comment by mkoval** [comment]
@ClintLiddick Can you take a look at the discussion above and offer you opinion on how we should distribute these models?

The low resolution models are ~800 MB. This is very close to the repository limit on Github. Perhaps we should consider hosting this on Gitlab or looking into using Gitlab's large file support?

**Comment by DavidB-CMU** [comment]
It has been suggested that we host these OpenRAVE models on our privately-hosted, publicly-available git server. 
The public web address would be something like: 
http://git.personalrobotics.ri.cmu.edu/groups/GROUP_NAME/REPO_NAME/
I think this structure is confusing. 

Previously when I've setup a central repository we used: 
http://company.com/git/REPO_NAME/ 
which is much better.

**Comment by ClintLiddick** [comment]
The URL would be https://git.personalrobotics.ri.cmu.edu/pr_data/REPO_NAME. It's the solution we have.

**Comment by DavidB-CMU** [comment]
So the words "/group/" or "/user/" gets dropped from the URL?  
What if you create a project called "foo" under a group, and then another user tries to create a project with the same name?

**Comment by ClintLiddick** [comment]
Yup. If the second "foo" is also under the same group, there will be an error and GitLab won't let you create it. You could create it under a different group or user.

**Comment by mkoval** [comment]
@DavidB-CMU @ClintLiddick What's the status of this?

**Comment by ClintLiddick** [comment]
https://git.personalrobotics.ri.cmu.edu/pr_data/ycb_objects

Everything I found is uploaded.

**Pull request closed without merging**
