### PR TITLE
Adding bookcase urdf and stl.

### PR DESCRIPTION
**Pull request by ClintLiddick**
@gilwoolee any reason not to merge this?

### CODE REVIEW

**Comment by gilwoolee** [comment]
I thought I'd add wheels to the bookcase but then postponed it. If wheels are necessary for the pantry demo to work, I can work on it this Friday.

**Comment by ClintLiddick** [comment]
Oh ok, that sounds good. Otherwise we'd have to always offset it from the floor in every demo anyway.

**Comment by gilwoolee** [comment]
Added wheels to the bookcase. Looks like this: [bookcase](https://drive.google.com/open?id=0BzWN-lwtVVPxTnZTZk9ULTUtUU0)

`wheels.urdf` is added but not actually used in `bookcase.urdf`; just copy-pasted the contents and added transformations. 

@ClintLiddick @brianhou Could you check and merge this? Thanks!

**Comment by jslee02** [comment]
> wheels.urdf is added but not actually used in bookcase.urdf; just copy-pasted the contents and added transformations.

It would be nice to add the comment to the `.urdf` files for the future reference.

**Review by brianhou — CHANGES_REQUESTED** [review]
- [x] Add comment to `bookcase.urdf` to explain that things are copied from `wheels.urdf`.

**Review by brianhou — APPROVED** [review]

**Comment by brianhou** [comment]
LGTM, merging.

**Pull request merged**
